---

- name: Ubuntu | add universe repository
  apt_repository:
    repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
    state: present
  when: ansible_distribution == 'Ubuntu'
