---

- name: Ubuntu | add universe repository
  ansible.builtin.apt_repository:
    repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Debian | update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: "{{ xrdp_apt_cache_valid | default('3600') }}"
  when: ansible_os_family == 'Debian'

# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931899#17
# https://askubuntu.com/questions/1239503/ubuntu-20-04-and-20-10-etc-securetty-no-such-file-or-directory
# https://forums.linuxmint.com/viewtopic.php?t=335853
- name: Remove error log about /etc/securetty
  ansible.builtin.replace:
    dest: /etc/pam.d/common-auth
    regexp: '^auth      [success=1 default=ignore]      pam_unix.so nullok_secure'
    replace: '^auth      [success=1 default=ignore]      pam_unix.so'
    mode: '0644'

- name: Ensure policykit-1 is present
  ansible.builtin.package:
    name: policykit-1
    state: present

# https://c-nergy.be/blog/?p=12073
- name: Fix freedesktop color managed device issue
  ansible.builtin.copy:
    src: 02-allow-colord.conf
    dest: /etc/polkit-1/localauthority.conf.d/02-allow-colord.conf
    mode: '0644'
