---
# https://help.ubuntu.com/community/xrdp

- name: Ensure xrdp package is present
  package:
    name: xrdp
    state: present

- name: setup xrdp.ini
  template:
    src: xrdp.ini.j2
    dest: /etc/xrdp/xrdp.ini
    mode: '0644'
    backup: yes
  notify:
    - restart xrdp

- name: setup xrdp window manager
  template:
    src: startwm.sh.j2
    dest: /etc/xrdp/startwm.sh
    mode: '0755'
    backup: yes
  notify:
    - restart xrdp
