---
# handlers file for juju4.xrdp

- name: Restart xrdp
  ansible.builtin.service: name=xrdp state=restarted
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )
