---

- name: Verify
  hosts: xrdp
  gather_facts: true
  tasks:
    - name: Debug | ansible_facts['virtualization_type']
      ansible.builtin.debug:
        var: ansible_facts['virtualization_type']
        verbosity: 1
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Validate that needed packages are present
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['xrdp'] is defined

    - name: Ensure xrdp.ini file is present
      ansible.builtin.stat:
        path: /etc/xrdp/xrdp.ini
      register: cfg
    - name: Validate config present
      ansible.builtin.assert:
        that: cfg.stat.exists and cfg.stat.size != 0

    - name: Ensure process is running
      ansible.builtin.command: pgrep -u xrdp xrdp
      register: ps
      changed_when: false
      failed_when: false
    - name: Validate ps output
      ansible.builtin.assert:
        that: ps.stdout | length > 0
      when: >
        not (ansible_facts['virtualization_type'] is defined and
              (ansible_facts['virtualization_type'] == "docker" or ansible_facts['virtualization_type'] == "containerd")
          )

    - name: Ensure ports are listening
      ansible.builtin.wait_for:
        host: "{{ item.h }}"
        port: "{{ item.p }}"
        timeout: 10
      with_items:
        - { h: localhost, p: 3389 }
      when: >
        not (ansible_facts['virtualization_type'] is defined and
              (ansible_facts['virtualization_type'] == "docker" or ansible_facts['virtualization_type'] == "containerd")
          )
