---

- name: Verify
  hosts: xrdp
  gather_facts: false
  tasks:
    - name: Gather package facts
      package_facts:
        manager: auto
    - name: Validate that needed packages are present
      assert:
        that: ansible_facts.packages['xrdp']

    - name: Ensure xrdp.ini file is present
      stat:
        path: /etc/xrdp/xrdp.ini
      register: cfg
    - name: Validate config present
      assert:
        that: cfg.stat.exists and cfg.stat.size != 0

    - name: Ensure process is running
      command: pgrep -u xrdp xrdp
      register: ps
      changed_when: false
    - name: Validate ps output
      assert:
        that: ps.stdout
      when: >
        not (ansible_virtualization_type is defined and
              (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
          )

    - name: Ensure ports are listening
      wait_for:
        host: "{{ item.h }}"
        port: "{{ item.p }}"
        timeout: 10
      with_items:
        - { h: localhost, p: 3389 }
      when: >
        not (ansible_virtualization_type is defined and
              (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
          )
